src/main/java/umc/cockple/demo/domain/member/domain/MemberParty.java
src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java
src/main/java/umc/cockple/demo/domain/party/domain/PartyAddr.java
src/main/java/umc/cockple/demo/domain/party/domain/PartyImg.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyAddrCreateCommand.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateCommand.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateRequestDTO.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateResponseDTO.java
src/main/java/umc/cockple/demo/domain/party/exception/MemberErrorCode.java
src/main/java/umc/cockple/demo/domain/party/exception/MemberException.java
src/main/java/umc/cockple/demo/domain/party/repository/PartyAddrRepository.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
src/main/java/umc/cockple/demo/global/s3/ImageService.java

사용자를 조회하고 이미지 업로드 처리를 하여 모임을 생성합니다.
close #{20} 
<br>
<br>
- Party 클래스에서 다중 선택을 하는 활동요일과 급수 구현 확인 부탁드립니다. 
<br>

[feat/#20] 모임 만들기 API 구현

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java

<br>
close #46 
<br>
<br>
<br>

[feat/#46] 내 대회 기록 상세조회 API 구현

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
src/main/java/umc/cockple/demo/domain/contest/domain/Contest.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordSimpleResponseDTO.java
src/main/java/umc/cockple/demo/domain/contest/repository/ContestRepository.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryService.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
src/main/java/umc/cockple/demo/global/enums/MedalType.java

<br>
전체 리스트
미입상 리스트
close #55 
<br>
<br>
<br>

[feat/#55] 내 대회 기록 리스트 조회 (전체, 미입상) API 구현

---

src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java

[feat/#86] 대표 주소 변경API 구현

---

src/main/java/umc/cockple/demo/domain/member/dto/CreateMemberAddrDTO.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java

- 추가된 주소가 자동으로 대표주소 설정
- 기존 대표주소 해제
<br>
close #98 
<br>
<br>
<br>

[refactor/#98] 주소 추가 로직 수정

---

src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
src/main/java/umc/cockple/demo/domain/member/domain/Member.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberExerciseRepository.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java

orphanRemover를 쓰면 코드가 줄어서 썼었는데 생각보다 관리가 어렵고, 영속성관리가 힘들다는 단점이 있었습니다. 잘만 쓰면 너무 유용할 거 같지만, 저는 아직 무지하기 때문에 구현 범위가 더 커지기 전에 제거했습니다!
잘 쓸 수 있는 정도까지 제 수준이 올라오면 다시 써보는걸루 .....
없애니까 모임 생성 잘 되었습니다!
없애고 양방향 작업 해야하는 부분 수정해주었습니다
<br>
close #138 
<br>
<br>
<br>

[refactor/#138]  orphanRemoval 제거

---

src/main/java/umc/cockple/demo/domain/bookmark/controller/BookmarkController.java
src/main/java/umc/cockple/demo/domain/bookmark/domain/ExerciseBookmark.java
src/main/java/umc/cockple/demo/domain/bookmark/repository/ExerciseBookmarkRepository.java
src/main/java/umc/cockple/demo/domain/bookmark/service/BookmarkCommandService.java
src/main/java/umc/cockple/demo/global/enums/ExerciseOrderType.java

- 운동 찜하기
- 운동 찜 해제하기
운동 찜하기
찜 해제하기
<br>
close #125 
<br>
<br>
<br>

[feat/#125] 운동 찜 관련 기능 구현

---

src/main/java/umc/cockple/demo/domain/notification/controller/NotificationController.java
src/main/java/umc/cockple/demo/domain/notification/converter/NotificationConverter.java
src/main/java/umc/cockple/demo/domain/notification/domain/Notification.java
src/main/java/umc/cockple/demo/domain/notification/dto/AllNotificationsResponseDTO.java
src/main/java/umc/cockple/demo/domain/notification/exception/NotificationErrorCode.java
src/main/java/umc/cockple/demo/domain/notification/exception/NotificationException.java
src/main/java/umc/cockple/demo/domain/notification/repository/NotificationRepository.java
src/main/java/umc/cockple/demo/domain/notification/service/NotificationCommandService.java
src/main/java/umc/cockple/demo/domain/notification/service/NotificationQueryService.java
src/main/java/umc/cockple/demo/global/enums/NotificationType.java

알림 전체 조회 로직 구현
<br>
close #160 
<br>
<br>
<br>

[feat/#160] 알림 전체 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/bookmark/service/BookmarkCommandService.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java
src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java

모임 삭제 시 해당 모임 관련 API를 수행하지 못하도록 검증 메서드를 추가했습니다.
<br>
close #175
<br>
<br>
<br>

[refactor/#175] 모임 활동상태 검증 메서드 추가

---

src/main/java/umc/cockple/demo/domain/notification/controller/NotificationController.java
src/main/java/umc/cockple/demo/domain/notification/dto/ExistNewNotificationResponseDTO.java
src/main/java/umc/cockple/demo/domain/notification/service/NotificationQueryService.java

읽지 않은 알림이 1개라도 존재하면 true 반환
<br>
close #161 
<br>
<br>
<br>

[feat/#161] 읽지 않은 알림 여부 조회

---

src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoom.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

<br>
클리어 모임 생성
모임 채팅방 자동으로 생성 완료
모임장은 자동으로 채팅방에 참여
close #217 
<br>
<br>
<br>

[feat/#217] 모임 생성 시 자동으로 모임 채팅방 생성 로직 구현

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseRecommendationCalendarDTO.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepositoryCustom.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepositoryCustomImpl.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java

사용자에게 추천할 운동을 캘린더 형태로 조회합니다.
조건
- 사용자가 속하지 않은 모임의 운동 중 참여하지 않은 운동
- 모임의 나이 조건이 맞을 것
<br>
필터
- 급수
정렬
- 위치
- 시간
<br>
필터
- 지역
- 급수
- 운동 스타일
- 활동 시간
정렬
- 최신순
- 참여 인원이 많은 순
<br>
- 콕플 추천
-> 위치가 가까운 순으로 정렬시키므로 distance 필드값이 존재.
- 필터 X(최신순)
- 필터(지역: 안 맞음), 최신순
- 필터(지역: 맞음), 최신순
- 필터(급수: 안 맞음), 최신순
- 필터(급수: 맞음), 최신순
- 필터(참여 타입: 안 맞음), 최신순
- 필터(참여 타입: 맞음), 최신순
- 필터(시간: 안 맞음), 최신순
- 필터(시간: 맞음), 최신순
- 필터 X(참여인원이 많은 순)
<br>
close #192 
<br>
<br>
<br>

[feat/#192] 새로운 운동 추천 캘린더 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/notification/converter/NotificationConverter.java
src/main/java/umc/cockple/demo/domain/notification/dto/AllNotificationsResponseDTO.java

응답에 원래 title이랑 data 필드가 없었어서 추가
<br>
close #255 
<br>
<br>
<br>

[fix/#255] 알림 전체 조회 응답에 data 필드 추가

---

src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoom.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

<br>
close #286 
<br>
<br>
<br>

[fix/#286] 모임 채팅방 저장 방식 변경

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java

<br>
close #302 
<br>
<br>
<br>

[fix/#302] 하드코딩->로그인 아이디로 변경

---

build.gradle
src/main/java/umc/cockple/demo/global/config/RedisConfig.java
src/main/java/umc/cockple/demo/global/config/redisTest/RedisTest.java
src/main/resources/application.yml

채팅에서 쓸 redis 설정 및 배포서버에 연결
<br>
close #305 
<br>
<br>
<br>

[feat/#305] redis 기본 설정 추가 및 도입

---

src/main/java/umc/cockple/demo/global/config/SecurityConfig.java

ws 경로를 임시로 허용합니다.
<br>
close #315 
<br>
<br>
<br>

[debug#315] 임시로 웹소켓 경로 허용

---

src/main/java/umc/cockple/demo/domain/member/exception/MemberErrorCode.java
src/main/java/umc/cockple/demo/global/jwt/domain/JwtTokenProvider.java

jwt null인 경우 예외처리 추가
스웨거로 테스트 할 수 있는 부분이 아니라서 실행이 문제 없이 되는 거만 보여드릴 수 있을 거 같습니다 ㅜㅜ
<br>
close #328 
<br>
<br>
<br>

[feat/#328]  JWT null인 경우 예외 처리

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseEditDetailDTO.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java

운동 상세 조회 API는 수정을 위한 정보를 제공하지 못해 운동 수정 정보를 제공하는 API입니다.
<br>
close #355 
<br>
<br>
<br>

[feat/#355] 운동 수정을 위한 조회 API 구현

---

src/main/java/umc/cockple/demo/global/oauth2/service/KakaoOauthService.java

프론트 테스트 용이성을 위해서 리프레시 토큰 재발급이 되는 텀을 줄였습니다!
<br>
close #405 
<br>
<br>
<br>

[chore/#405] 리프레시 토큰 재발급 텀 줄이기
