Cockple/Cockple_BE

build.gradle
src/main/java/umc/cockple/demo/global/exception/GeneralException.java
src/main/java/umc/cockple/demo/global/exception/GlobalExceptionHandler.java
src/main/java/umc/cockple/demo/global/response/BaseResponse.java
src/main/java/umc/cockple/demo/global/response/code/BaseErrorCode.java
src/main/java/umc/cockple/demo/global/response/code/status/CommonErrorCode.java
src/main/java/umc/cockple/demo/global/response/dto/ErrorReasonDTO.java

전역적 예외 핸들러를 구현했습니다.
1. 비즈니스 로직 예외 (GeneralException)
2. @Valid 검증 실패 (MethodArgumentNotValidException) - @RequestBody
3. @Validated 검증 실패 (ConstraintViolationException) - @RequestParam, @PathVariable
4. URL의 타입 변환 실패 (MethodArgumentTypeMismatchException)
5. 필수 파라미터 누락 (MissingServletRequestParameterException)
6. JSON 파싱 오류 (HttpMessageNotReadableException)
7. 최종 예외 (Exception)
<br>
close #3 
<br>
<br>
- 이거 에러 코드 추가적으로 만들었는데 의견 부탁드립니다!
<br>

[feat/#3] 글로벌 예외 처리 로직 구현

---

src/main/java/umc/cockple/demo/global/exception/GlobalExceptionHandler.java

문제: Ambiguous @ExceptionHandler method mapped for [MissingServletRequestParameterException] 에러 해결
원인: Spring Boot 3.x에서 ResponseEntityExceptionHandler의 기본 핸들러와 커스텀 @ExceptionHandler가 충돌
해결 방법
주요 변경사항
1. @ExceptionHandler → @Override 패턴으로 변경
- handleMissingServletRequestParameter() - 필수 파라미터 누락
- handleMethodArgumentNotValid() - @Valid 검증 실패
- handleHttpMessageNotReadable() - JSON 파싱 오류
2. 반환 타입 통일: 모든 핸들러를 ResponseEntity<Object>로 표준화
3. 메서드 시그니처 업데이트: Spring Boot 3.x 호환
<br>
<br>
close #6 
<br>
<br>
Spring Boot 3.x에서는 ResponseEntityExceptionHandler를 상속받은 클래스에서 Spring 기본 예외를 처리할 때 @Override 방식을 사용해야 한다고 하네요 ㅠㅠ
<br>

[fix#6] GlobalExceptionHandler에서 @ExceptionHandler 충돌 문제 해결

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
src/main/java/umc/cockple/demo/domain/contest/domain/Contest.java
src/main/java/umc/cockple/demo/domain/contest/domain/ContestVideo.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteCommand.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDeleteResponseDTO.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
src/main/java/umc/cockple/demo/domain/contest/repository/ContestRepository.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java

<br>
이미지랑 동영상도 잘 삭제 되었습니다.
close #44 
<br>
<br>
<br>

[Feat/#44] 대회 기록 삭제 API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseManagerCancelRequestDTO.java
src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java

모임장 또는 부모임장이 운동의 특정 참가자의 참가를 취소시킵니다.
검증
- 운동이 존재하는지
- 멤버가 존재하는지
- 운동이 이미 시작하진 않았는지
- 멤버가 모임장 또는 부모임장인지
그 후, 참가자가 게스트인지 여부를 프론트에서 넘겨준 boolean값을 통해 확인한 뒤,
참가자를 제거하고, 순서를 재정렬시킵니다.
<br>
close #51 
<br>
<br>
<br>

[feat/#51] 특정 회원 운동 취소 API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseDeleteResponseDTO.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java

모임장이 운동을 삭제하는 API를 구현합니다.
검증
- 운동이 존재하는지
- 운동 삭제 권한이 있는지
<br>
close #57 
<br>

[feat/#57] 운동 삭제 API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java

기존의 nowCapacity 필드를 통한 계산에서
Guest와 MemberExercise의 .size()의 합으로 참여자 수를 계산합니다.
<br>
close #61 
<br>
<br>
연산 때문에 성능이 조금 떨어질 수는 있으나 이게 데이터 안전성에 좋은 방향이라고 생각했습니다!
의견 부탁드립니다!
<br>

[refactor/#61] 운동 참여자 수 계산 로직 수동 증가에서 사이즈 계산으로 변경

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordDetailResponseDTO.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryService.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java

<br>
영상, 기록 다 비공개 일때
영상, 기록 다 공개 일때
기록만 비공개 일때
close #70 
<br>
<br>
<br>

[feat/#70] 다른 회원의 대회 기록 상세조회 API 구현

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java

기존에 내 대회 기록 리스트 조회에서 조금 수정해서 통합으로 만들었습니다.
<br>
미입상 조회
전체 리스트 조회
close #73  
<br>
<br>
<br>

[feat/#73] 다른 회원의 대회 기록 리스트 (전체, 미입상) API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
src/main/java/umc/cockple/demo/domain/exercise/domain/ExerciseAddr.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseAddrUpdateCommand.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseUpdateCommand.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseUpdateRequestDTO.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseUpdateResponseDTO.java
src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java

모임장이 운동을 수정하는 API를 구현합니다.
검증
- 멤버가 모임장의 권한인지
- 운동이 이미 시작한 운동인지
- 운동의 시간이 제대로 설정되어 있는지
<br>
close #66 
<br>
<br>
엔티티에서 DTO에 접근하는 게 싫어서 command 패턴을 도입했는데, 뭔가 투머치인거 같기도 하고요...
create에서도 같은 방법을 사용했는데, 정답은 잘 모르겠습니다.
<br>

[feat/#66] 운동 수정 API 구현

---

src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
src/main/java/umc/cockple/demo/domain/member/domain/Member.java
src/main/java/umc/cockple/demo/domain/member/exception/MemberErrorCode.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java

회원 주소 삭제 기능
- 대표 주소 삭제 불가 (UI상으로는 프론트에서 1차 검증을 진행하지만 백엔드에서도 진행)
- 회원의 주소는 최소 1개 이상 존재하도록 구현
대표주소 삭제 시도시
다른 주소는 삭제 성공
<br>
close #94 
<br>
<br>
<br>

[feat/#94] 회원 주소 삭제 API 구현

---

src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateCommand.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateRequestDTO.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

모임 생성 API의 이미지 업로드를 받아오는 방식을 변경했습니다.
- requestPart -> requestBody
- 기존의 DTO, 정적팩토리메서드 등 관련 코드 변경
<br>
close #89
<br>
<br>
- 없습니다!
<br>

[refactor/#89] 모임 생성 API 이미지 업로드 방식 변경

---

src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/domain/Exercise.java
src/main/java/umc/cockple/demo/domain/exercise/domain/Guest.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseCancelDTO.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseGuestInviteDTO.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseJoinDTO.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
src/main/java/umc/cockple/demo/domain/member/domain/MemberExercise.java

운동 내 순번을 필드를 따로 두는 대신
createdAt 필드를 통해서 GET할 때 정렬하는 방식으로 구현하겠습니다.
운동 신청
게스트 초대
게스트 초대 취소
운동 신청 취소
<br>
close #102 
<br>
<br>
<br>

[refactor#102] MemberExercise와 Guest에서 participantNum 필드 제거

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/exception/ExerciseErrorCode.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
src/main/java/umc/cockple/demo/domain/member/domain/Member.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java

- 급수 검증 로직 추가
- 나이 검증 로직 추가
<br>
close #103 
<br>
<br>
Sorting이나 Paging이 필요없는 경우 Lazy Loading하는 엔티티를 Fetch join으로 한 번에 가져오면 좋을 거 같습니다!
<br>

[feat/#103] 운동 신청 API에서 검증 로직 추가

---

src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java
src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

- 모임 신청 시, 모임의 급수 조건에 해당하는 인원만 신청 가능하도록 검증하는 로직을 구현했습니다.
- 모임 신청 시, 모임 유형에 해당하는 성별만 신청 가능하도록 검증하는 로직을 구현했습니다.
<br>
close #110
<br>
<br>
- 급수와 성별로 검증되는지 테스트 완료했습니다.
<br>

[feat/#110] 모임 신청 API 검증 로직 추가 구현

---

src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
src/main/java/umc/cockple/demo/domain/member/converter/MemberConverter.java
src/main/java/umc/cockple/demo/domain/member/domain/MemberAddr.java
src/main/java/umc/cockple/demo/domain/member/dto/CreateMemberAddrDTO.java
src/main/java/umc/cockple/demo/domain/member/dto/GetAllAddressResponseDTO.java
src/main/java/umc/cockple/demo/domain/member/dto/GetMyProfileResponseDTO.java
src/main/java/umc/cockple/demo/domain/member/dto/GetNowAddressResponseDTO.java
src/main/java/umc/cockple/demo/domain/member/dto/GetProfileResponseDTO.java
src/main/java/umc/cockple/demo/domain/member/service/MemberQueryService.java

- 회원의 대표주소 (Main 화면 상단에 띄우는) 조회 
- 프로필 수정 시 나오는 회원의 주소 전체 조회
1-1. 회원의 대표주소 조회 (건물명 존재)
1-2. 회원의 대표주소 조회 (건물명 부재 -> 건물명은 NULL 가능, 없는 경우에는 도로명 사용)
2. 회원의 등록된 주소 전체 조회
<br>
close #96 
<br>
<br>
<br>

[Feat/#96] 회원 주소 조회 관련 API 구현

---

src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyCreateDTO.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinActionDTO.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyJoinDTO.java
src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java

모임 가입 신청이 승인된 사용자들의 목록 조회를 구현했습니다. 
- 기존의 모임 가입 신청 목록 조회 API를 활용하여 구현했습니다. 쿼리 파라메터로 PENDING 또는 APPROVED를 넣어 구분하여 출력되도록 구현했습니다.
- status에 PENDING 또는 APPROVED가 들어가지 않을 경우 예러 처리를 했습니다.
- APPROVED( 승인된 목록)인 경우에만 updatedAt이 출력되도록 했습니다.
<br>
close #124 
<br>
<br>
- 없습니다!
<br>

[feat/#124] 모임 가입 승인 멤버 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseDetailDTO.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
src/main/java/umc/cockple/demo/domain/exercise/repository/GuestRepository.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
src/main/java/umc/cockple/demo/domain/member/domain/MemberExercise.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberExerciseRepository.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
src/main/java/umc/cockple/demo/global/enums/ExerciseMemberShipStatus.java

운동 상세 정보를 조회하는 API를 구현했습니다.
기초 검증
- 운동이 존재하는 지
- 조회하는 대상이 멤버인지
비즈니스 로직
- 조회하는 대상이 매니저(모임장)일경우 운동 수정 및 삭제 UI가 보여야하기에 관련 데이터를 조회합니다.
- 운동의 기초 정보를 생성합니다.
- 멤버 참가자와 게스트 참가자를 별도로 DB에서 조회한 후, 이를 ParticipantInfo 객체 List로 만듭니다.
- 그 리스트를 합치고 시간 순으로 정렬해 전체 참여자 리스트를 생성합니다.
- 전체 참여자 리스트를 운동의 최대 인원을 기준으로 참여자, 대기자로 구분하고 번호를 부여합니다.
- 이를 반환합니다.
<br>
close #78 
<br>
<br>
-> 이는 N개의 정보를 한 번에 가져와 성능상 효과적입니다.
<br>

[feat/#78] 운동 상세 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/dto/PartySimpleDTO.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java

사용자가 가입한 모든 내 모임 목록을 조회합니다. 위 경우, 간략화하여 모임명과 지역 정보만 조회합니다.
<br>
close #131
<br>
<br>
<br>

[feat/#131] 내 모임 조회 (간략화) API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/ExerciseMyGuestListDTO.java
src/main/java/umc/cockple/demo/domain/exercise/repository/GuestRepository.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java

- 내가 초대한 게스트 목록을 불러온 뒤,
- 운동 전체 참여자 목록을 조회해서 운동 내 순번을 조회합니다.
- 내 게스트 목록과 운동 내 순번, 초대자 이름으로 게스트 정보 리스트를 생성합니다.
- 그 후, 통계를 계산하고,
- Response로 반환합니다.
<br>
close #132 
<br>
<br>
<br>

[feat/#132] 내가 초대한 운동 게스트 조회 API 구현

---

.gitignore
src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/MyExerciseCalendarDTO.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
src/main/resources/application.yml

내가 참여하고 있는 운동 캘린더를 조회합니다.
<br>
close #153 
<br>

[feat/#153] 내 운동 캘린더 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/bookmark/controller/BookmarkController.java
src/main/java/umc/cockple/demo/domain/bookmark/converter/BookmarkConverter.java
src/main/java/umc/cockple/demo/domain/bookmark/dto/GetAllPartyBookmarkResponseDTO.java
src/main/java/umc/cockple/demo/domain/bookmark/repository/PartyBookmarkRepository.java
src/main/java/umc/cockple/demo/domain/bookmark/service/BookmarkQueryService.java
src/main/java/umc/cockple/demo/domain/notification/domain/Notification.java

- 찜한 모임 전체 조회
- 운동 많은순, 최신순, 오래된 순 정렬 구현
운동 많은 순
오래된 순
최신순
<br>
close #152 
<br>
<br>
<br>

[feat/#152] 찜한 모임 전체 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/bookmark/repository/ExerciseBookmarkRepository.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/PartyExerciseCalendarDTO.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java

모임 운동 캘린더 조회 API에서 누락된 필드인 찜 여부 반환 로직을 구현했습니다.
찜을 하지 않았을경우 false를 반환합니다.
<br>
close #166 
<br>
<br>
<br>

[feat/#166] 모임 운동 캘린더 조회 API에 찜 여부 추가

---

src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java

조회할 게 없을 때 나머지 로직을 처리하지 않고 바로 빈 응답을 반환하도록 변경합니다.
- 내가 초대한 게스트 조회
1. 초대한 게스트가 있을 때
2. 초대한 게스트가 없을 때
- 모임 운동 캘린더 조회
1. 운동이 없는 모임
2. 운동이 있는 모임
- 내 운동 캘린더 조회
1. 운동이 없는 사용자
2. 운동이 있는 사용자
<br>
close #149 
<br>
<br>
운동 상세 조회는 운동의 여부를 확인하면서 예외를 던지므로 따로 패턴 도입을 하지 않았습니다.
<br>

[feat/#149] 운동 도메인에 빈 응답 조기 반환(Early Return) 패턴 도입

---

src/main/java/umc/cockple/demo/domain/exercise/controller/ExerciseController.java
src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/MyPartyExerciseCalendarDTO.java
src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseCommandService.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
src/main/java/umc/cockple/demo/global/enums/MyPartyExerciseOrderType.java

내 모임 운동 캘린더 조회 API를 구현했습니다.
응답 -> 주별 -> 날짜별 -> 운동 아이템의 중첩 구조를 가지고 있으며,
멤버 id 값으로 내가 속한 모임의 id를 조회한 후,
운동 리스트를 조회합니다.
운동 찜 여부와 운동의 참여인원 수를 별개의 쿼리로 가져온 뒤에,
Converter에서 날짜별로 그룹핑하며 orderType에 따라 정렬을 진행합니다.
참여 인원 수는 피그마 화면에는 필요없지만 제대로 정렬된 걸 확인하기 위해 반환하도록 했습니다.
- 인기 많은순
- 최신순
<br>
close #165 
<br>
<br>
<br>

[feat/#165] 내 모임 운동 캘린더 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/member/repository/MemberPartyRepository.java
src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyMemberDTO.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java
src/main/java/umc/cockple/demo/global/enums/Role.java

특정 모임의 멤버 목록을 조회합니다.
- 모임장, 부모임장이 가장 상단에 오도록 정렬했습니다
- 사용자 본인 여부를 파악할 수 있도록 하여 모임 탈퇴 시 사용하도록 구현했습니다. 
<br>
close #178
<br>
<br>
- 없습니다.
<br>

[feat/#178] 모임 멤버 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/MyExerciseCalendarDTO.java
src/main/java/umc/cockple/demo/domain/exercise/dto/PartyExerciseCalendarDTO.java

응답 -> 주별 -> 날짜별 -> 운동 아이템 순의 DTO 계층 구조를
- 내 운동 캘린더 조회 API
- 모임 운동 캘린더 조회 API
에 적용했습니다.
- 내 운동 캘린더 조회 API
- 모임 운동 캘린더 조회 API
<br>
close #177 
<br>
<br>
<br>

[feat/#177] 캘린더 조회 API에서 날짜별로 아이템 묶기

---

src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

모임장이 특정 멤버를 모임에서 삭제합니다.
<br>
close #137
<br>
<br>
<br>

[feat/#137] 모임 멤버 삭제 API 구현

---

src/main/java/umc/cockple/demo/domain/member/repository/MemberAddrRepository.java
src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/repository/PartyRepository.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java

사용자에게 추천되는 모임 목록을 조회합니다.
- 추천 기준 1) 사용자의 급수, 지역, 나이대를 기반으로 필터링을 걸어 맞춤형 모임을 추천합니다. ex) 경기도/파주시라면 경기도인 사람에게만 추천 목록으로 조회됨
- 추천 기준 2) 키워드 맞는거 있는 순으로 상위 노출
- 이미 가입한 모임은 추천되지 않도록 구현했습니다.
<br>
close #188
<br>
<br>
<br>

[feat/#188] 모임 추천 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateDTO.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandService.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java

<br>
이미지, 동영상 삭제
이미지, 동영상 추가
close #199 
<br>
<br>
<br>

[refactor/#199] 대회 기록 수정 API에서 이미지 업로드 분리

---

src/main/java/umc/cockple/demo/domain/exercise/repository/ExerciseRepository.java
src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseQueryService.java
src/main/java/umc/cockple/demo/domain/member/domain/Member.java
src/main/java/umc/cockple/demo/domain/party/domain/Party.java

멤버의 나이와 모임의 나이 조건을 검증할 때, 멤버는 나이, 모임은 출생년도의 값을 비교하여 에러가 생겼습니다.
이를 출생년도로 통일하여 해결했습니다.
DB 멤버 칼럼값
DB 파티 칼럼값
운동 참여 신청 API
새로운 운동 추천 API
2번 멤버 사용
<br>
close #224 
<br>
<br>
<br>

[debug#224] 나이 검증 출생년도 비교로 변경 및 관련 필드명 변경

---

src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoomMember.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

<br>
탈퇴는 잘되고요
회원이 탈퇴 해도 메세지 내용이랑 이름은 유지하기 위해서 메세지 저장 방식을
chat_room_member와 chat_message 끼리 연관관계 삭제했습니다.
그래서 디비에
ALTER TABLE chat_message
DROP FOREIGN KEY FKjtrl0cyo3rxu4bcg3f17fdpm5;
ALTER TABLE chat_message
DROP COLUMN chat_room_member_id;
이거 해주셔야 돼요!
close #227 
<br>
<br>
<br>

[feat/#227] 모임 탈퇴 시, 자동으로 채팅방 퇴장 코드 구현

---

src/main/java/umc/cockple/demo/domain/contest/controller/ContestController.java
src/main/java/umc/cockple/demo/domain/contest/converter/ContestConverter.java
src/main/java/umc/cockple/demo/domain/contest/domain/ContestImg.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordCreateDTO.java
src/main/java/umc/cockple/demo/domain/contest/dto/ContestRecordUpdateDTO.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestCommandServiceImpl.java
src/main/java/umc/cockple/demo/domain/contest/service/ContestQueryServiceImpl.java
src/main/java/umc/cockple/demo/domain/image/dto/ImageUploadRequestDTO.java

<br>
이미지 저장할때 key만 보내는 걸로
응답은 url로
close #236 
<br>
<br>
이걸로 교체 했는데 괜찮을까요?
아니면 그냥 String으로 할까요? 지피티는 확장에는 DTO가 낫다고 하긴 하는데욤..
--> String으로 결정
<br>

[fix/#236] 대회 이미지 저장 방식 변경

---

src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberRepositoryCustom.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberRepositoryCustomImpl.java
src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyMemberSuggestionDTO.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java

- 모임장이 자신의 모임에 초대할 만한 신규 멤버를 추천받습니다. (급수 / 나이 / 지역)
- 검색을 통해 해당하는 급수의 멤버만을 조회합니다.
- 이미 모임에 소속되어 있거나 가입 신청 대기 중인 유저는 추천 목록에서 자동으로 제외됩니다.
<br>
close #232
<br>
<br>
<br>

[feat/#232] 신규 멤버 추천 API 구현

---

build.gradle
src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
src/main/java/umc/cockple/demo/domain/chat/enums/WebSocketMessageType.java
src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
src/main/java/umc/cockple/demo/global/config/WebSocketConfig.java

클라이언트는 /ws/chats 경로로 웹소켓 연결을 진행할 수 있습니다.
포스트맨에서 테스트를 할 때는 SockJS 설정 때문에 끝에 /websocket url을 붙였습니다.
<br>
close #248 
<br>
<br>
<br>

[feat/#248] 웹소켓 기본 설정 및 연결 관리 구현

---

src/main/java/umc/cockple/demo/domain/member/controller/MemberController.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
src/main/java/umc/cockple/demo/global/config/SecurityConfig.java
src/main/java/umc/cockple/demo/global/jwt/domain/JwtTokenProvider.java
src/main/java/umc/cockple/demo/global/oauth2/service/KakaoOauthService.java

프론트 개발자분의 요청 + 개발할때마다 시큐리티 컨피그를 수정해야하는 번거로움이 있어 id가 1인 멤버를 디폴트로 하여 토큰을 발급하는 api를 만들었습니다!
<br>
close #264 
<br>
<br>
<br>

[feat/#264] 개발자 테스트용 토큰 발급

---

src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/domain/PartyInvitation.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyInviteActionDTO.java
src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

사용자가 모임의 초대를 처리(수락/거절)하는 API를 구현합니다.
<br>
close #262
<br>
<br>
<br>

[feat/#262] 모임 초대 처리 API 구현

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/domain/ChatRoomMember.java
src/main/java/umc/cockple/demo/domain/chat/dto/ChatRoomDetailDTO.java
src/main/java/umc/cockple/demo/domain/chat/enums/MessageType.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatMessageRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java

초기 채팅방 조회 api를 구현했습니다.
채팅방에 들어가면 호출하는 api입니다.
채팅방이 존재하는 지, 내가 채팅방에 들어갈 권한이 있는 지 검증합니다.
그 후 채팅방 정보, 최신 메시지 50개 정보, 참여자 정보를 조회하여 반환합니다.
잘못된 파라미터 값
<br>
close #279 
<br>
<br>
이거 한 번씩 부탁드립니다! 저희 key만 저장하기로 해서 그거 반영했습니다.
<br>

[feat/#279] 초기 채팅방 조회 API 구현

---

src/main/resources/application.yml

카카오톡으로 받은 모임 기본이미지로 이미지 업로드 api 실행 중 413 에러 발생 
스프링 서버, 배포 서버의 nginx에 body 크기를 크게 지정해서 디버깅
결과
근데 nginx에서도 괜찮은지는 배포서버로 실행해야해서 merge 후 알 수 있을 거 같습니다 ㅜㅜ
<br>
close #289 
<br>
<br>
<br>

[debug/#289] 전송 이미지 크기 설정

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/dto/ChatMessageDTO.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatMessageRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatCommandServiceImpl.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java

과거 메시지 조회 API를 구현합니다.
초기 데이터를 조회하는 API는 따로 있으므로 커서 값이 null인 경우는 고려하지 않습니다.
가장 마지막으로 읽은 메시지의 id값을 커서로 지정하여 그 값보다 작은(즉, 옛날) 메시지들을 size만큼 가져옵니다.
<br>
close #280 
<br>
<br>
<br>

[feat/#280] 과거 메시지 조회 API 구현

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/dto/ChatMessageDTO.java
src/main/java/umc/cockple/demo/domain/chat/dto/PartyChatRoomDTO.java
src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatMessageRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatCommandServiceImpl.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java
src/main/resources/application.yml

<br>
채팅방 목록을 lastMessage 아이디 기준으로 정렬하도록 했습니다.
민턴이즈에 새로운 채팅이 왔을 경우, 민턴이즈의 lastMessage 시간이 더 최신이기 때문에 민턴이즈가 클리어 채팅방보다 위에 있습니다.
close #256 
<br>
<br>
<br>

[feat/#256] 모임 채팅방 목록 조회 slice 기반 무한스크롤 구현

---

build.gradle
src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatWebSocketService.java
src/main/java/umc/cockple/demo/domain/member/repository/MemberRepository.java
src/test/java/umc/cockple/demo/domain/chat/ChatWebSocketHandlerTest.java
src/test/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandlerTest.java

1. 사용자가 메시지를 전송하면
문자열로 전송된 json을 objectMapper로 json으로 변환해 Request 객체에 담습니다.
2. 세션에서 멤버 id를 추출합니다.
3. Request 객체에서 메시지의 타입을 검사해 전송임을 확인합니다.
4. 서비스 단에서 기초 검증을 한 뒤에 메시지를 DB에 저장합니다.
5. 그 후 다른 사용자에게 전달할 데이터들을 반환합니다.
6. 채팅 -> 멤버 -> 웹소켓 으로 접근이 가능하므로 채팅방 세션에서 각 멤버별 세션을 추출하고, 병렬연산으로 각 멤버에게 메시지를 전달합니다.
<br>
close #250 
<br>
<br>
<br>

[feat/#250] 메시지 전송 기능 구현

---

src/main/java/umc/cockple/demo/domain/chat/dto/MemberConnectionInfo.java
src/main/java/umc/cockple/demo/domain/chat/dto/WebSocketMessageDTO.java
src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
src/main/java/umc/cockple/demo/domain/chat/events/ChatMessageSendEvent.java
src/main/java/umc/cockple/demo/domain/chat/events/ChatRoomSubscriptionEvent.java
src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatRoomMemberRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatWebSocketService.java
src/main/java/umc/cockple/demo/domain/chat/service/SubscriptionService.java

채팅방에 들어갈경우 SUBSCRIBE를 보내 채팅방을 구독하는 로직입니다.
서비스끼리 순환 참조가 일어나 이벤트를 기반으로 주고받는 방식으로 진행했습니다.
채팅방을 구독하는 것과 메시지를 보내는 것 모두 handleTextMessage에서 스위치문으로 이벤트를 발행합니다.
ChatEventListener가 이벤트를 받아 각각의 서비스로 호출합니다.
채팅방 메시지 보내기 -> ChatWebSocketService에서 메시지 저장 -> SubscriptionService에서 브로드캐스트
채팅방 구독 -> SubscriptionService에서 구독 처리
멤버 1, 2 웹소켓 연결
멤버 1, 2 채팅방 구독 -> 채팅방 목록에서 채팅방 하나를 누른 상황
멤버 1이 채팅을 보냄
-> 멤버 2에게 채팅이 감
멤버 2가 채팅을 보냄
-> 멤버 1에게 채팅이 감
<br>
close #265 
close #307 
<br>
<br>
<br>

[feat/#265] 채팅방 구독 로직 구현

---

src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
src/main/java/umc/cockple/demo/domain/chat/interceptor/JWTWebSocketAuthInterceptor.java
src/main/java/umc/cockple/demo/global/config/WebSocketConfig.java

웹소켓 연결 시 스프링 시큐리티 필터를 지나는 대신
인터셉터에서 JWT로 검증합니다.
또한, 이 JWT에서 memberId를 받아옵니다.
테스트할때는 쿼리 파라미터로 ?token=토큰값 을 추가하면 됩니다.
<br>
close #306 
<br>
<br>
<br>

[feat/#306] JWT를 활용해 웹소켓 연결 인증 단계 구현

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessage.java
src/main/java/umc/cockple/demo/domain/chat/domain/ChatMessageFile.java
src/main/java/umc/cockple/demo/domain/chat/domain/DownloadToken.java
src/main/java/umc/cockple/demo/domain/chat/dto/ChatDownloadTokenDTO.java
src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
src/main/java/umc/cockple/demo/domain/chat/repository/ChatFileRepository.java
src/main/java/umc/cockple/demo/domain/chat/repository/DownloadTokenRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatCommandService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatFileService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java

다운로드 토큰을 발급하는 API를 구현합니다.
<br>
close #287
<br>
<br>
<br>

[feat/#287] 다운로드 토큰 발급 구현

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/chat/exception/ChatErrorCode.java
src/main/java/umc/cockple/demo/domain/chat/repository/DownloadTokenRepository.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatCommandService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatFileService.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java
src/main/java/umc/cockple/demo/domain/image/service/ImageService.java

파일을 다운로드하는 API를 구현합니다.
<br>
close #288
<br>
<br>
<br>

[feat/#288] 파일 다운로드 구현

---

src/main/java/umc/cockple/demo/domain/chat/events/ChatEventListener.java
src/main/java/umc/cockple/demo/domain/chat/events/ChatRoomSubscriptionEvent.java
src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
src/main/java/umc/cockple/demo/domain/chat/service/SubscriptionService.java

채팅방을 구독 해제하는 이벤트입니다.
채팅방에 구독 해제하고 나면 그 채팅방에 실시간 메시지가 전송되어도 메시지가 오지 않습니다.
채팅방에서 목록 뷰로 넘어갈 때 사용하면 될 거 같습니다.
연결 - 구독 - 메시지 보내기 - 메시지 보내기
연결 - 구독 - 메시지 받음 - 구독 해제(메시지 안 옴)
<br>
close #300 
<br>
<br>
<br>

[feat/#300] 채팅방 구독 해제 로직

---

src/main/java/umc/cockple/demo/domain/chat/controller/ChatController.java
src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatFileServiceImpl.java
src/main/java/umc/cockple/demo/domain/image/controller/ImgController.java
src/main/java/umc/cockple/demo/domain/image/dto/FileUploadDTO.java
src/main/java/umc/cockple/demo/domain/image/dto/ImageUploadDTO.java
src/main/java/umc/cockple/demo/domain/image/dto/ImageUploadResponseDTO.java
src/main/java/umc/cockple/demo/domain/image/exception/S3ErrorCode.java
src/main/java/umc/cockple/demo/domain/image/service/ImageService.java
src/main/java/umc/cockple/demo/global/enums/DomainType.java
src/main/java/umc/cockple/demo/global/enums/ImgType.java

- 파일 다운로드를 S3Object를 직접 가져오는 방식으로 리팩토링했습니다.
- Pre-signed URL (임시 비밀번호가 포함된 URL) 방식으로 구현하다가 헤더 불일치로 인하여 생기는 오류로 인하여 S3Object를 직접 가져오는 getObject 방식으로 변경했습니다.
- getObject 방식이 메타데이터나 파일을 직접 다룰 수 있기에 보안상 더 안전하고 코드도 간소화되나, 비용적으로 Pre-signed URL이 더 좋기에 추후에 리팩토링 고려 중입니다.
- 파일 업로드 API를 구현했습니다.
파일 다운로드
파일 업로드
<br>
close #311
<br>
<br>
<br>

[feat/#311] 파일 다운로드 리팩토링 / 파일 업로드 API 구현

---

src/main/java/umc/cockple/demo/domain/member/domain/Member.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
src/main/java/umc/cockple/demo/global/config/SecurityConfig.java
src/main/java/umc/cockple/demo/global/exception/RestAuthenticationEntryPoint.java
src/main/java/umc/cockple/demo/global/oauth2/service/KakaoOauthService.java
src/main/java/umc/cockple/demo/global/security/filter/JwtAuthenticationFilter.java

- 기존에 status만 변경했었는데, status에 따라 시큐리티 필터에서 검증하도록 변경
회원 탈퇴
탈퇴 후 다른 요청에 접근시 401 에러
<br>
close #322 
<br>
<br>
<br>

[feat/#322] 탈퇴 회원 시큐리티 필터에서 검증

---

src/main/java/umc/cockple/demo/domain/party/controller/PartyController.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyKeywordDTO.java
src/main/java/umc/cockple/demo/domain/party/exception/PartyErrorCode.java
src/main/java/umc/cockple/demo/domain/party/repository/PartyKeywordRepository.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandService.java
src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

모임의 키워드를 등록하는 API를 구현합니다.
<br>
close #296
<br>
<br>
- 없습니다.
<br>

[feat/#296] 키워드 추가 API 구현

---

src/main/java/umc/cockple/demo/domain/party/repository/PartyRepositoryCustomImpl.java

모임 지역(addr2)을 특정 지역으로 조회 시, 모임 지역(addr2)가 전체인 모임도 의미 상 포함되므로 조회되도록 수정합니다.
<br>
close #326
<br>
<br>
- 없습니다.
<br>

[fix/#326] 특정 지역으로 조회 시, addr2가 전체인 모임도 조회되도록 수정

---

src/main/java/umc/cockple/demo/domain/exercise/service/ExerciseValidator.java

운동 신청 시 급수 조건이 맞지 않아도 신청할 수 있도록 검증 메서드를 주석처리 했습니다.
<br>
close #348 
<br>
<br>
<br>

[fix#348] 운동 신청 시 급수 조건이 맞지 않더라도 신청할 수 있도록 변경

---

src/main/java/umc/cockple/demo/domain/party/service/PartyCommandServiceImpl.java

- 모임 생성 시에도 급수 조건을 따지지 않도록 수정 (사용자의 급수가 급수없음인 경우 급수 조건을 따질 수 없고, 사용자가 원하는 멤버의 급수대가 본인과 일치하지 않을 수 있기에 요구사항 변경)
- 모임 가입신청 처리 시, 이미 멤버인지 검증하는 로직 추가
<br>
close #361
<br>
<br>
- 없습니다
<br>

[fix/#361] 모임 관련 검증 수정사항 반영

---

src/main/java/umc/cockple/demo/domain/chat/converter/ChatConverter.java
src/main/java/umc/cockple/demo/domain/chat/service/ChatQueryServiceImpl.java

개인 채팅방 목록 조회
개인 채팅방 이름 검색
모임 채팅방 목록 조회
모임 채팅방 이름 검색
<br>
close #362 
<br>
<br>
<br>

[fix/#362] 현재 (목록/개인) 채팅방 목록 조회 및 검색 API에서 채팅방이 없을 때 에러 던지는 걸 빈 배열 던지는 걸로 반환

---

src/main/java/umc/cockple/demo/global/config/WebSocketConfig.java

프론트 배포 주소에서 웹소켓 cors 허용이 되어있지 않아 에러가 발생했습니다.
이를 배포 주소를 추가하여 해결합니다.
테스트는 프론트 측에 여쭤봐야 할 거 같습니다!
<br>
close #359 
<br>
<br>
<br>

[debug#359] 웹소켓 설정에서 프론트 배포 주소 CORS 허용

---

src/main/java/umc/cockple/demo/domain/member/repository/MemberRepositoryCustomImpl.java

현재 신규멤버 추천 API의 급수 검색에서 급수 문자 전체를 입력해야만 조회가 되는 것을 급수 문자에 포함된 글자 입력만으로도 조회되도록 수정합니다.
ex) A조 멤버 검색 시, 기존에는 "A조" 모두 입력해야만 조회 -> "A" 입력만으로도 조회되도록 수정
<br>
close #339
<br>
<br>
- 없습니다!
<br>

[fix/#339] 급수 검색에서 포함된 글자만으로도 조회되도록 수정 

---

src/main/java/umc/cockple/demo/domain/party/converter/PartyConverter.java
src/main/java/umc/cockple/demo/domain/party/dto/PartyDetailDTO.java
src/main/java/umc/cockple/demo/domain/party/service/PartyQueryServiceImpl.java

- 모임 미가입 사용자가 가입 신청을 했을 시, 가입신청 버튼 비활성화를 위해 가입 신청 여부를 담은 필드 추가
- 모임장 채팅방으로의 연결을 위한 모임장 ID 필드 추가
<br>
close #375
<br>
<br>
- 없습니다.
<br>

[fix/#375] 모임 상세 조회 응답 필드 추가

---

src/main/java/umc/cockple/demo/domain/member/domain/Member.java
src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
src/main/java/umc/cockple/demo/domain/member/service/MemberQueryService.java

로컬로는 되는데 배포서버에서 DB관련 문제가 생겨서 다시 올립니다 ㅠㅡㅠ 
수정
조회
<br>
close #379 
<br>
<br>
<br>

[fix/#379] 프로필 사진 수정 오류

---

src/main/java/umc/cockple/demo/domain/exercise/converter/ExerciseConverter.java
src/main/java/umc/cockple/demo/domain/exercise/dto/MyExerciseListDTO.java

내 참여 운동 리스트 조회 API에 참여자들의 성별 급수 필드를 추가했습니다.
<br>
close #407 
<br>
<br>
<br>

[fix/#407] 내 운동 리스트 조회 API에 급수 필드 추가

---

build.gradle
src/main/java/umc/cockple/demo/domain/chat/handler/ChatWebSocketHandler.java
src/main/java/umc/cockple/demo/domain/chat/service/websocket/RedisSubscriptionService.java
src/main/java/umc/cockple/demo/domain/chat/service/websocket/SubscriptionService.java
src/main/resources/application.yml

- 현재 구독 정보를 메모리 기반으로 관리하고 있었는데, 이는 서버가 껐다가 켜질경우 구독 정보가 초기화되는 문제가 있었습니다.
- 이제 Redis에 구독 정보를 관리함으로써 서버가 꺼졌다가 켜져도 구독 정보가 그대로 유지됩니다.
- 구독 정보가 쌓여 문제가 될 수 있으므로 TTL 설정을 2시간으로 진행하여, 활성화되지 않은 지 2시간이 되면 자동으로 구독 정보를 삭제합니다.
- 또한 브라우저 종료 시 구독 정보를 정리하지 않음으로써 사용자 UX를 더 향상시켰습니다.
- 서버가 꺼졌을 때 자연적으로 발생하는 웹소켓 에러는 따로 잡아 DEBUG 레벨로 로그를 찍음으로써 로그를 더 깔끔하게 개선했습니다.
<br>
close #343 
<br>
<br>
<br>

[feat/#343] Redis 기반 채팅방 구독 관리 시스템 구축

---

src/main/java/umc/cockple/demo/global/config/RedisConfig.java
src/main/resources/application.yml

채팅방 목록 조회 및 검색에서 Redis 캐싱을 사용하면서 Jackson에서 직렬화 문제가 발생했습니다.
설정을 추가하여 이를 해결합니다.
<br>
close #413
<br>
<br>
<br>

[debug/#413] Redis에서 Jackson 직렬화 문제 해결

---

src/main/java/umc/cockple/demo/domain/member/service/MemberCommandService.java
src/main/resources/application.yml

기존에 imgKey에 대해 null 여부만 체크해서 profileImg의 key에 유효하지 않은 값이 들어가는 경우 발생
로그인시 프로필사진 미지정 경우 (프로필 null)
이후 사진 넣어도 적용 (원래 여기서 에러 발생)
<br>
close #421 
<br>
<br>
<br>

[fix/#421] profile imgKey null, 비어있는 값 모두 체크
